### PR TITLE
fix(node-http-handler): fix invalid usage of parsed url

### PR DESCRIPTION
**Pull request by Defman**
*[issue](https://github.com/aws/aws-sdk-js-v3/issues/6495)*

*Description of changes:*

Nodejs `URL` is not fully compatible with `http.RequestOptions` see https://github.com/nodejs/node/issues/39738

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Defman** [comment]
@kuhe is this something you could have a look at?

**Review by kuhe — APPROVED** [review]

**Review by hpmellema — APPROVED** [review]

**Comment by kuhe** [comment]
in https://www.npmjs.com/package/@smithy/node-http-handler/v/3.2.3

**Comment by Defman** [comment]
Amy chance og getting it bumped in https://github.com/aws/aws-sdk-js-v3 ?

**Comment by kuhe** [comment]
yes, but it will happen at a later date. A lockfile update or other type of fresh install would bring in the fix.

**Comment by Defman** [comment]
Yea, I feel a bit stupid right now... had been trying to get my fork to work with npm overrides all day... however after it got merged I should of course just run `npm upgrade @smithy/node-http-handler` to update the lock file...

**Pull request merged**
